### ISSUE TITLE
Calendar for DB maintenance

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/cor-cm#39] opened 2024-08-08 17:24 UTC
We'll need to discuss briefly how this would ideally be implemented. Possibilities:

1. Slack notifications
2. An Outlook calendar, either e.g. LTDS or separate

**Comment by kbowaterskelly** [comment] 2024-08-12 23:09
This is a duplicate of #136

**Comment by kbowaterskelly** [comment] 2024-08-15 03:55
1. What day of the month and time would we like to set for DB maintenance?
2. What format(s) would we like the calendar in? Slack, Outlook, etc.

**Comment by kbowaterskelly** [comment] 2024-08-21 00:15
Flattened RDS production maintenance schedule to 08:00 UTC Monday, created an outlook calendar. Noting here a lot of pending maintenance on our DBs which may require further review.

**Closed as completed** 2024-08-29 00:14 UTC
